### ISSUE TITLE
How to refer to the editor in angular?

### ISSUE THREAD

**Issue by ShaiTeller** [isonet/angular-jsoneditor#2]
From what i know in your original version (just javascript), u would create the editor and have a reference for it. But I'm not quite sure how to refer to the editor in the angular version.

For example if I wanna do things like editor.set(json) or anything along those lines.

**Comment by isonet** [comment]
Please check out this example: https://jsfiddle.net/kdhky4v9/2/

```
<angular-jsoneditor ng-model="data" options="options"></angular-jsoneditor>
```

`data` is going to be your (parsed) json object. No need for .set, if you modify the object the view is automatically updated and vice versa.

**Comment by ShaiTeller** [comment]
thanks for the reply, but what I really meant is not for setting the data, but for other functions that the editor offers. 

for example: [https://github.com/josdejong/jsoneditor/issues/211](url)

editor.editor.setOptions({maxLines: 100});

how would i do this in the angular version?

**Comment by samsfisher** [comment]
Do you know how to access the instance

**Comment by SwapnilChidrawar** [comment]
Hi @ShaiTeller ,

 I also want the same behaviour that you were searching for angular + versions . If you have solution for maxLines could you please suggest us ?
